services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DataBase__Username}
      - POSTGRES_PASSWORD=${DataBase__Password}
      - POSTGRES_DB=${DataBase__DateBase}
    ports:
      - "5432:5432"
    restart: always
  dogapi:
    container_name: dogapi
    environment:
      - DataBase__Username=${DataBase__Username}
      - DataBase__Password=${DataBase__Password}
      - DataBase__DateBase=${DataBase__DateBase}
      - DataBase__Port=${DataBase__Port}
    build: ./src
    ports:
      - "80:80"
      - "443:443"